[build]
  command = "cd alquilerBicicletasFrontend && npm run build"
  publish = "alquilerBicicletasFrontend/dist/alquiler-bicicletas-fronted"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:8085/api/:splat"
  status = 200